### ISSUE TITLE
SyntaxError while importing TweetFeels

### ISSUE THREAD

**Issue by agneet42** [uclatommy/tweetfeels#38]
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tweetfeels import TweetFeels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tweetfeels/__init__.py", line 1, in <module>
    from .tweetdata import TweetData, TweetBin
  File "/usr/local/lib/python3.5/dist-packages/tweetfeels/tweetdata.py", line 146
    df = df.groupby(pd.TimeGrouper(freq=f'{int(binsize/second)}S')).size()
                                                                ^
SyntaxError: invalid syntax

Any hints?
Thank you,

**Comment by uclatommy** [comment]
Hi @agneet42,
TweetFeels requires at minimum python 3.6 because it uses f-strings, which were introduced in that version.
