### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Muggsie** [uclatommy/tweetfeels#44]
Looks like a very interesting app. Any guidance in how to do the initial setup to begin testing? For ex where do I place my auth keys? I have looked through the whole folder.

**Comment by Muggsie** [comment]
When I try to run python3 setup.py I get this error mesage: 

`➜  ~ python3 /Users/main/Desktop/black_magic/tweetfeels/setup.py
Traceback (most recent call last):
  File "/Users/main/Desktop/black_magic/tweetfeels/setup.py", line 12, in <module>
    exec(compile(open(filename, "rb").read(), filename, 'exec'))
  File "/Users/main/Desktop/black_magic/tweetfeels/version_1.py", line 1, in <module>
    from tweetfeels import TweetFeels
  File "/Users/main/Desktop/black_magic/tweetfeels/tweetfeels/__init__.py", line 2, in <module>
    from .tweetlistener import TweetListener, Tweet
  File "/Users/main/Desktop/black_magic/tweetfeels/tweetfeels/tweetlistener.py", line 2, in <module>
    from tweepy.streaming import StreamListener
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
`
